# Generated by Django 4.2.5 on 2024-10-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='screenshot',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
